channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10.*
  - bioconda::flye=2.9.*
  - bioconda::samtools=1.20.*
  - bioconda::minimap2=2.28.*
  - bioconda::racon=1.5.*
  - pip
  - pip:
    - -r requirements-linters.txt
    - "PyYAML >=6.0, < 6.1"
    - "scikit-learn >=1.5.0, <1.6"
    - "pysam >= 0.22.1, <0.23"
    - "pyfastx >= 2.1.0, <2.2"
    - "pandas >= 2.2, < 2.3"